### ISSUE TITLE
multiple reports for golang

### ISSUE THREAD

**Issue by ievans** [returntocorp/semgrep#128]
On sgrep-rules branch ie/golang2: the pattern `if (false) { ... }` reports three times on a single line:
(see PR for file contents: https://github.com/returntocorp/sgrep-rules/pull/54/files)

```
sgrep-rules (ie/golang2)> sgrep-lint --strict --no-rewrite-rule-ids -f go/deadcode/useless-eqeq.yaml go/deadcode/useless-eqeq.go
running 2 rules from 1 yaml files (0 yaml files were invalid)
go/deadcode/useless-eqeq.go:8 eqeq-is-bad - useless comparison operation `y == y` or `y != y`
go/deadcode/useless-eqeq.go:13 hardcoded-eq-true-or-false - useless if statement, always the same behavior
go/deadcode/useless-eqeq.go:13 hardcoded-eq-true-or-false - useless if statement, always the same behavior
go/deadcode/useless-eqeq.go:13 hardcoded-eq-true-or-false - useless if statement, always the same behavior
```

**Comment by brendongo** [comment]
Doesn't look like this exists anymore. Assuming it was fixed by https://github.com/returntocorp/semgrep/pull/398

**Comment by ievans** [comment]
@brendongo - I think this was "fixed" by just doing a `uniq` on the output, not by investigating what caused the underlying issue. Agreed this can slide for now though.
