### ISSUE TITLE
Simplify boolean patterns

### ISSUE THREAD

**Issue by DrewDennison** [returntocorp/semgrep#148]
Issue for discussion:

I think we can make the patterns a lot simpler. i.e. `pattern-either` can become `or` and `pattern-not` could just be `not`

**Comment by dan5382** [comment]
Just saw this sorry for the late follow up. 
All looks good except its hard conceptually to think of 'pattern-not' Is there a better way we can incorporate that?

**Comment by ievans** [comment]
This was discussed already by @mschwager and others; I think we agreed on what we wanted to do so I'm going to close the ticket @DrewDennison
