### ISSUE TITLE
DTL/Jinja2 parsing support

### ISSUE THREAD

**Issue by ievans** [returntocorp/semgrep#182]
For the Django checks we are writing, it would be great to have sgrep support for the Django templating langauge and Jinja2 (a popular alternative): 
https://docs.djangoproject.com/en/3.0/topics/templates/

**Comment by aryx** [comment]
What do we want for this? Just the ability to parse those template files and
get an AST that we can sgrep on for everything between {{ }} ? one issue is that
some stuff inside {{ }} are not complete stmt/expr, I saw for example
{{ if cond }} ..... {{ endif }}
which is not even Python, so not sure what I can parse here.

**Comment by minusworld** [comment]
Basically, we want to support writing checks like our [jinjalint checks](https://checks.bento.dev/en/latest/jinjalint/anchor-href-template-variable/) or like [this one](https://github.com/returntocorp/sgrep-rules/issues/76).

I could imagine rewriting https://checks.bento.dev/en/latest/jinjalint/anchor-href-template-variable/ as something like:

```
<a ... href="{{ $X }}" ...>
```
in sgrep.

**Comment by nbrahms** [comment]
@aryx Here's the jinja2 template spec / example:

https://jinja.palletsprojects.com/en/2.11.x/templates/

It's not Python at all. I tried to find BNF, but no dice :(

**Comment by nbrahms** [comment]
@minusworld 

Please provided minimal examples

**Comment by minusworld** [comment]
Example for https://github.com/returntocorp/sgrep-rules/issues/76:
```html
<div>
  {{ variable|striptags|safe }}
</div>
```

Another example:
```html
<div>
  <a href="{{ link|striptags|safe }}">click me</a>
</div>
```

Potential pattern:
```html
{{ $VAR|striptags|safe }}
```

**Comment by minusworld** [comment]
Example for https://github.com/returntocorp/sgrep-rules/issues/240, use `json_script`:
```html
<!-- Bad Example -->
<script>
  const data = {{ data|safe }};
</script>
```

```html
<!-- Good Example -->
{{ data|json_script:"data" }}
<script>
const data = JSON.parse(document.getElementById('data').textContent);
</script>
```

Potential pattern:
```
pattern-inside: <script>...</script>
pattern: $DATA = {{ $X|safe }}
```

**Comment by minusworld** [comment]
Example for https://github.com/returntocorp/sgrep-rules/issues/78, avoid `{% autoescape on %}`
```html
<div>
  {% autoescape on %}
    {{ content }}
  {% autoescape off %}
</div>
```

Potential pattern:
```yaml
pattern-inside: {% autoescape on %}...
pattern: {{ ... }}
```

**Comment by ievans** [comment]
@minusworld what do you thinking about closing this out now that we have the generic mode?

**Comment by minusworld** [comment]
sgtm
