### ISSUE TITLE
FirebaseCustomRemoteModel remoteModel =       new FirebaseCustomRemoteModel.Builder("your_model").build(); FirebaseModelDownloadConditions conditions = new FirebaseModelDownloadConditions.Builder()         .requireWifi()         .build(); FirebaseModelManager.getInstance().download(remoteModel, conditions)         .addOnSuccessListener(new OnSuccessListener<Void>() {             @Override             public void onSuccess(Void v) {               // Download complete. Depending on your app, you could enable               // the ML feature, or switch from the local model to the remote               // model, etc.             }         });

### ISSUE THREAD

**Issue by jonatanmurga** [returntocorp/semgrep#1941]
**Describe the bug**

**To Reproduce**
Steps to reproduce the behavior, ideally a link to https://semgrep.dev:

**Expected behavior**

**Screenshots**

**What is the priority of the bug to you?**
Is this a P0 (blocking your adoption of Semgrep or workflow), P1 (important to fix or quite annoying), P2 (regular bug that should get fixed)?

**Environment**
If not using semgrep.dev: are you running off docker, an official binary, a local build?

**Comment by dlukeomalley** [comment]
Hi @jonatanmurga, thanks for opening a ticket. Was this submitted accidentally? I'll close it preemptively, but please feel free to reopen with details and a description if it was intentional! 🙏
