### ISSUE TITLE
Certain patterns result in two matches

### ISSUE THREAD

**Issue by nbrahms** [returntocorp/semgrep#199]
**Describe the bug**
Certain patterns (see repro) return two results on the same expression.

**To Reproduce**
This is on Python code:

Rule:
```yaml
pattern: target(..., kw=$X, ...)
```

Code:
```python
target(other_kw="foo", kw="bar")
```

Result: See message printed twice for same line of code.

**Expected behavior**
I expect only one match.

**Desktop (please complete the following information):**
Docker `returntocorp/sgrep` image `2772f96a29b9`

**Comment by DrewDennison** [comment]
@ievans I'm planning to fix in the python code but lmk if this is something you think should be passed off to @aryx

**Comment by ievans** [comment]
@DrewDennison as I read this, I think @aryx should weight in

**Comment by ievans** [comment]
See also #128

**Comment by DrewDennison** [comment]
ha we searched for `twice` not `three`

**Comment by DrewDennison** [comment]
This is now deduped in the python code so closing for now
