### ISSUE TITLE
 integrate tree-sitter java parser into sgrep

### ISSUE THREAD

**Issue by minusworld** [returntocorp/semgrep#2]

**Comment by aryx** [comment]
there is already a Java parser in  sgrep; it parses 98% code.
the title should be integrate tree-sitter java parser into sgrep

**Comment by ulziibay** [comment]
Final code lives in https://github.com/returntocorp/ocaml-tree-sitter/tree/master/proto

**Comment by dlukeomalley** [comment]
Closing until broader tree-sitter work lands. Java is already supported. CC @DrewDennison @nbrahms
