### ISSUE TITLE
Sgrep Fails when last line of a python file is a comment

### ISSUE THREAD

**Issue by brendongo** [returntocorp/semgrep#240]
**Describe the bug**
Sgrep fails with LexicalError when the last line of a python file is a comment. But does not fail when there is a newline after the comment

**To Reproduce**

Pattern: $X == $X
Code: 
```
if 2 == 2:
    print('hello')
#
```
Or code:
```
if 2 == 2:
    print('hello')
#

```

 https://sgrep.live/gpR vs https://sgrep.live/QwJ

**Expected behavior**
I expect sgrep to work even if the last line is a comment

**Additional context**

**Comment by brendongo** [comment]
FWIW sgrep running locally fails silently so it looks like there was just no matches. The sgrep.live showed an error message

**Comment by ievans** [comment]
cc @brendongo : this is another python parsing related issue

**Comment by brendongo** [comment]
Also fails when the last line is code but contains a comment https://semgrep.live/kRX

**Comment by brendongo** [comment]
Realworld Example: https://github.com/1337/yesterday-i-learned/blob/72fa6abe6edc73fd8d086baede20f2a00ccb3f3d/scripts/enum_test.py
