### ISSUE TITLE
sgrep cannot parse import statements in javascript pattern

### ISSUE THREAD

**Issue by ievans** [returntocorp/semgrep#250]
Imports work just fine in .js files, but fail as part of the pattern:

`import {x} from “foo”`

https://sgrep.live/xxl
```
in .sgrep.yml, pattern in rule pattern_id can't be parsed for language js: import {x} from "foo"
1 invalid patterns found inside rules; aborting
```

**Comment by aryx** [comment]
A bit more complicated, but probably the sgrep_spatch_pattern in parser_js.mly is too restrictive
and does not allow to derive the import directive. Make sure your fix does not introduce additional shift/reduce conflict.

**Comment by ievans** [comment]
Missing support for `{x}` in import declarations as part of the pattern; re-opening.

**Comment by brendongo** [comment]
https://sgrep.live/k0P looks like the issue with the sgrep.live above was missing semi-colon.

**Comment by DrewDennison** [comment]
@ievans I can't repro this https://semgrep.live/Po0

**Comment by DrewDennison** [comment]
and https://semgrep.live/J0k works fine
