### ISSUE TITLE
Port Python sgrep testsuite to the other languages

### ISSUE THREAD

**Issue by aryx** [returntocorp/semgrep#251]
Right now most bugfixes and enhancements are done first on Python because that's the language
we target first, which means most of the tests are in tests/python/, but we should try to port
those tests to the other languages (when they can apply).

**Comment by aryx** [comment]
In some cases there are unique tests in tests/js/ or tests/go, but for those too we should try each
time to port them to the other languages (In some case we can factorize the sgrep file at least and put it under tests/GENERIC/).

**Comment by aryx** [comment]
Ideally we would have a nice display matrix indicating the missing tests for each language (@ulziibay started that, but right now it's just a count for each language; would be nice to be able to see the actual missing tests)

**Comment by DrewDennison** [comment]
@ulziibay is this done?

**Comment by ulziibay** [comment]
Closing this as the work is done https://github.com/returntocorp/semgrep/blob/develop/docs/matrix.md. We should make sure to generate the matrix continously
