### ISSUE TITLE
update docs to reflect support for typescript and JSX

### ISSUE THREAD

**Issue by ievans** [returntocorp/semgrep#295]
We support typescript and JSX; we should update the docs to mention that and also explain the language that will be parsed under --lang js versus --lang ts, for instance.

**Comment by aryx** [comment]
JSX support should be good, but typescript support is partial.

**Comment by DrewDennison** [comment]
Example failing TS: https://semgrep.live/5Nk

I was pleasantly surprised the example hello-world from create-react-app works but I don't know how to query it: https://semgrep.live/GBG

**Comment by aryx** [comment]
Can you create separate issue to parse JSX pattern as toplevel pattern.
This should be fixable.

**Comment by DrewDennison** [comment]
https://github.com/returntocorp/semgrep/issues/661

**Comment by brendongo** [comment]
Closing while typescript support is "partial"
