### ISSUE TITLE
Aliasing for javascript object properties

### ISSUE THREAD

**Issue by inkz** [returntocorp/semgrep#299]
It would be awesome to have some sort of aliasing for objects in order to catch multiple ways of defining an object property with one rule
https://sgrep.live/v2R
https://sgrep.live/d05

the idea is to use one rule 
```
$F.one = 1;
```
to catch cases as different as:
```javascript
var foo = {
    one: 1,
    two: 2,
    three: 3
}
```

```javascript
var foo = {}
foo.one = 1
foo.two = 2
foo.three = 3
```
or more complex examples:

with spread operator
```javascript
var bar = {
    one: 1
}

var foo = {
    ...bar,
    two: 2,
    three: 3
}
```

or even Object.assign
```javascript
var bar = {
    one: 1
}

var foo = Object.assign({two: 2, three: 3}, bar)
```

it can help following a certain object across the code e.g if it is not intended to be passed to a dangerous function

```
$F.one = "sensitive-data";
...
sink($F);
```

```javascript
var bar = {
    one: 'sensitive-data'
}

var foo = {
    ...bar,
    two: 2,
    three: 3
}

sink(foo)
```

**Comment by DrewDennison** [comment]
@minusworld does your equivalence work support this use case?

**Comment by minusworld** [comment]
> @minusworld does your equivalence work support this use case?

I haven't tried something like this yet; I am not sure if equivalences able to handle this situation. @aryx would know better; tagging for comment

**Comment by aryx** [comment]
This can be solved more easily with tainting.

**Comment by aryx** [comment]
:wave:

**Comment by inkz** [comment]
:wave:

**Comment by dlukeomalley** [comment]
@IagoAbal @aryx  - I saw the mention of solving this with tainting. Does the new taint work help here?

**Comment by IagoAbal** [comment]
@dlukeomalley yes I believe the new taint mode solves these problems, you can e.g. specify `{..., one: 1, ...}` and `$X.one = 1` as sources of taint and track if they go into some sink.

**Comment by dlukeomalley** [comment]
@inkz Closing for now then. Please re-open if you find @IagoAbal's suggestion does not suit your needs 🙏

**Comment by inkz** [comment]
sure! thanks :+1:
