### ISSUE TITLE
Helpful error messages when invalid pattern supplied

### ISSUE THREAD

**Issue by clintgibler** [returntocorp/semgrep#308]
Copied from https://github.com/returntocorp/sgrep/issues/255#issuecomment-595520023.

I had a similar issue to @jtmelton in that some of my first sgrep search patterns were fragments and thus were not parsed by sgrep. It would be nice to have some error message when parsing fails that gives common failure reasons and examples of proper search terms.

If sgrep could detect what the user is trying to do and give specific advice, e.g. `$FOO(` => "Hey it looks like you're trying to match a function call, try `$FOO(...)`", that would be 🚀

But for now, having a generic error message that gives examples of how to do each common pattern should be sufficient (e.g. assignments, function calls, function definitions, conditionals, maybe a handful of others).

Related issue, in that it's also about improving ease of use / minimizing gotchas: #252.

**Comment by dlukeomalley** [comment]
@clintgibler Do you feel the semgrep.live "next steps" solves this ticket?

![image](https://user-images.githubusercontent.com/605906/83812805-fed2d780-a670-11ea-999a-cc18ee0b05c9.png)

**Comment by ievans** [comment]
cc @rcoh who is working on this and @clintgibler who filed

**Comment by ievans** [comment]
Thanks to @rcoh 's work I'm going to close this -- we're ever so much better now
