### ISSUE TITLE
Allow specifying types in patterns

### ISSUE THREAD

**Issue by clintgibler** [returntocorp/semgrep#309]
Copied from https://github.com/returntocorp/sgrep/issues/255#issuecomment-595520023.

## Is your feature request related to a problem? Please describe.
When a user is writing an sgrep expression, they may wish to only match a specific type, for example, in a variable assignment, function call, etc.

This can already be done with string literals, for example:

~~~python
# python

$X = "..." # X is any hard coded string
exec("...", ...) # first arg to exec is hard coded string
~~~

But it should be possible for any type and in any language.

According to @aryx (https://github.com/returntocorp/sgrep/issues/255#issuecomment-595782077), this currently works for ints/floats, in Python only.

~~~yaml
# https://github.com/returntocorp/sgrep-rules/blob/develop/python/smells/sleep.yaml
rules:
  - id: arbitrary-sleep
    patterns:
      - pattern-not: time.sleep($F(...))
      - pattern-either:
        - pattern: |
             time.sleep($X: int)
        - pattern: |
             time.sleep($X: float)
    message: "time.sleep() call; did you mean to leave this in?"
    languages: [python]
    severity: ERROR
~~~

~~~python
# https://github.com/returntocorp/sgrep-rules/blob/develop/python/smells/sleep.py

# ruleid:arbitrary-sleep
t.sleep(5)
# ruleid:arbitrary-sleep
t.sleep(0.1)
# todoruleid:arbitrary-sleep
time.sleep("bad")
~~~

## Describe the solution you'd like
I would like to be able to specify types when it's important for the code I'm matching.

For typed languages, sgrep could use existing syntax:

~~~java
// java
int x = $VAL;

public static void $FOO(int $VAR, ...) { ... }
~~~

For typed languages, sgrep should be able to handle some simple cases without doing fancy type inference, just using the AST, e.g. for constants.

One challenge pointed out by @aryx is that we need to find an sgrep type syntax that doesn't conflict with the syntax of the host language. 

I propose the following:

* In cases where types can be specified reusing syntax of the host language, sgrep does that.
* In cases where that's not possible, for example, in an expression context, sgrep supports an additional `pattern` clause, like `pattern-type` or `pattern-metavar-type`, that allows the user to say: "this metavar should have this type."

Here's an example, based on @jtmelton's work (https://sgrep.live/4xL):

~~~yaml
rules:
  - id: assignment-comparison
    patterns:
      - pattern: if ($X = $Y) { ... }
      - pattern-metavar-type:
        "$Y": "bool_literal" 
    message: "The value of `$X` is being ignored and will be used in the conditional test"
    languages: [java]
    severity: ERROR
~~~

It seems like this approach could work, if metavars were enforced to be the same across each pattern (#176).

## Describe alternatives you've considered
This functionality, in some cases, could perhaps be (poorly) approximated using `pattern-where-python` to introspect on the value of what's matched.

However, I think this is a common enough use case that it merits first class sgrep support.

**Comment by ievans** [comment]
@inkz has requested, along these lines, that the inference work r2c has already done for Javascript (in https://github.com/returntocorp/stadt) be available within the sgrep query system.

**Comment by clintgibler** [comment]
Inference work / leveraging external type checkers would be an interesting and potentially quite useful addition.

But for v1, is that necessary?

Does the sgrep AST contain type info when it encounters a primitive / literal (e.g. strings, ints, floats, doubles, bytes, ...)? I believe semantic and most other parsers I've used have this type info where the literal is (not necessarily later where the variable it's assigned to is used).

And for typed languages, I would guess you'd have type info at least at method/class/variable definitions, though it may not be easily accessible later in the code where that entity is used.

~~~java
int x = 5; // we can see the int_literal and type here
...
// Might need to do some local resolving to know x's type here
System.out.println(x); 
~~~

**Comment by mschwager** [comment]
@aryx @emjin I think this is done? At least v1 is, and if we have more specific requests we can always create a new issue.

**Comment by jtmelton** [comment]
@mschwager is there documentation for this yet? I'd like to test it out, but not sure what it looks like

**Comment by mschwager** [comment]
> @mschwager is there documentation for this yet? I'd like to test it out, but not sure what it looks like

Hi John, it's currently documented under our experimental features: [Typed Metavariables](https://github.com/returntocorp/semgrep/blob/develop/docs/experimental.md#typed-metavariables).

**Comment by jtmelton** [comment]
> Hi John, it's currently documented under our experimental features: [Typed Metavariables](https://github.com/returntocorp/semgrep/blob/develop/docs/experimental.md#typed-metavariables).

:+1: thanks!

**Comment by jtmelton** [comment]
@mschwager  a quick question on this example (https://semgrep.live/Orwk/) that @clintgibler put together. Line 5 and 15 are correctly found now (great!). Maybe should be a different issue, but what do I do to get lines 22, 24, and 26 to be found as well? They are the same issue, just with boolean conditions in the conditional clause.

**Comment by mschwager** [comment]
> @mschwager a quick question on this example (https://semgrep.live/Orwk/) that @clintgibler put together. Line 5 and 15 are correctly found now (great!). Maybe should be a different issue, but what do I do to get lines 22, 24, and 26 to be found as well? They are the same issue, just with boolean conditions in the conditional clause.

Great question! You can use the [Deep Expression Operator](https://github.com/returntocorp/semgrep/blob/develop/docs/pattern-features.md#deep-expression-operator). I've modified your example a bit to make use of that operator: https://semgrep.live/5rXj/

Although, it appears that we're treating `if((s = true) || 1 == 1)` vs. `if(s = true || 1 == 1)` differently here. I'll create a separate issue to track this bug :+1:

**Comment by jtmelton** [comment]
Excellent - thank you! I'll watch that one as well.

**Comment by jtmelton** [comment]
@mschwager Also note that line 26 was missed in the example you made as well
