### ISSUE TITLE
Overridden Python method should cause sgrep result

### ISSUE THREAD

**Issue by dlukeomalley** [returntocorp/semgrep#313]
**Describe the bug**
On line 40, I expect sgrep to return a result because `_()` was overwritten to not be equal to `django.utils.translation.ugettext`:

https://sgrep.live/WpA

**Comment by dlukeomalley** [comment]
@ievans and I chatted about this offline. The consensus is that it's complex to do robustly, consider:

```python
if __name__ == 'main' and math.random() > 0.5:
    def _(bla):
        pass
_('foo')
```

**Comment by brendongo** [comment]
Note that this works when in function scope https://sgrep.live/pYN

**Comment by dlukeomalley** [comment]
As originally filed this issue is resolved!
