### ISSUE TITLE
Golang import aliasing

### ISSUE THREAD

**Issue by minusworld** [returntocorp/semgrep#327]
**Describe the bug**
Golang has the ability to rename imports. It does not appear that sgrep currently handles this.

**To Reproduce**
1. Go to https://sgrep.live/nrO

**Expected behavior**
In Python, we can refer to things by their fully-qualified name. In Go, things are a bit more nuanced because packages are automatically referred to only by the package and not the namespace. For example, importing `text/template` is referred to in Go code as `template`. This is problematic when we want to check for the existence of something like `html/template` and `text/template` in the same code, because one of these must be aliased.

In Go, packages are aliased like so:
```go
import (
    htemplate "html/template"
    ttemplate "text/template"
)
```

**Comment by aryx** [comment]
What if the code use import ("html/template")
and later do
template.func()?
how do you want to write the pattern? what code equivalence you want?
It maybe be nice to just write template.func(...) and that it handles automatically
the different import form, but then you have the problem that it will match also
a template.func(...) from a template imported from "test/template".

We don't have the problem in Python because Python requires fully qualified names
(unless you alias it), so in the code you would have
html.template.func() or text.template.func().

**Comment by minusworld** [comment]
I can imagine two approaches that are feasible:

1. Use metavariables
```golang
import(
    $HTML "html/template"
    "text/template"
)
```

2. Use fully-qualified name
```golang
import(
    "html/template"
    "text/template"
)
...
html.template.Exec(...)
```

**Comment by minusworld** [comment]
Proposed hack:

```golang
import (
    $HTML "html/template"
    $TEXT  "text/template"
)
...
$HTML.Exec(...)
```

**Comment by minusworld** [comment]
Tried the above hack, but it appears that ... in not considered valid in `import`: https://sgrep.live/p90
Removed the ... and the pattern is now valid, but it does not match: https://sgrep.live/2Aq
Being as explicit as possible, it still does not match: https://sgrep.live/jDl

**Comment by ulziibay** [comment]
@minusworld : coming to this from https://github.com/returntocorp/sgrep/issues/411.  There is more demand for supporting this! I am happy to take this on!

**Comment by ulziibay** [comment]
@minusworld i closed my PR for supporting metavar in import declarations, because it a pretty big feature spanning multiple language. I am not going to be able to implement that. Feel free to close this ticket or leave it open to be reprioritized! 
```
import (
    $HTML "html/template"
    $TEXT  "text/template"
)
...
$HTML.Exec(...)
```

**Comment by mschwager** [comment]
Reopening since this never got completed and is a worthwhile feature IMO.

**Comment by aryx** [comment]
This works now at least: https://semgrep.dev/s/Rr1e/?version=develop

**Comment by aryx** [comment]
and this example should now work on develop: https://semgrep.dev/s/jDl
