### ISSUE TITLE
Upgrade ocaml to latest stable branch

### ISSUE THREAD

**Issue by dlukeomalley** [returntocorp/semgrep#348]
**Is your feature request related to a problem? Please describe.**
Following along on https://github.com/priv-kweihmann/meta-sca/issues/126#issuecomment-606244962, let's consider upgrading sgrep to use the latest stable ocaml release.

**Comment by aryx** [comment]
The main issue I think is the use of camlp4 in pfff which was made obsolete.
There is already a ticket for that in pfff:
https://github.com/returntocorp/pfff/issues/65

**Comment by aryx** [comment]
I've removed the dependency to camlp4 and try to publish a new OPAM package hopefully working with recent OCaml versions (e.g., OCaml 4.10).
See https://github.com/ocaml/opam-repository/pull/16114

**Comment by aryx** [comment]
I've pushed a new OPAM pfff package compatible with recent OCaml versions.
It's merged at https://github.com/ocaml/opam-repository/pull/16125
Only thing remaining is to update our Dockerfile and CI to not switch create 4.07.3 but
just use 4.10.0 or 4.09.1 if we want to live a bit less on the edge.

**Comment by nbrahms** [comment]
@aryx Is this done?

**Comment by aryx** [comment]
Not sure. @DrewDennison may know. Not following what are the current build script.
@rcoh also. We should be compatible with ocaml > 4.05 now, no need to opam switch create 4.07.1 anymore.

**Comment by rcoh** [comment]
We now build on OCaml 4.10.0, 4.10.0-static-flambda on Linux.
