### ISSUE TITLE
[Python] Sgrep cannot match `with` statement when used with pattern-inside

### ISSUE THREAD

**Issue by ulziibay** [returntocorp/semgrep#356]
**Describe the bug**
When `pattern-inside` is used, sgrep matching is incorrect for `with` statement.  https://sgrep.live/Bxx shows that sgrep is able to match `with` statements.

**To Reproduce**
https://sgrep.live/AzL

**Expected behavior**
I expect the matching to give the same result regardless of `pattern-inside` 

**Screenshots**

**Environment**
If not using sgrep.live: are you running off docker, an official binary, a local build?

**Comment by aryx** [comment]
weird indeed

**Comment by ulziibay** [comment]
Seems to be fixed already! Closing
