### ISSUE TITLE
Support dataflow for constants in conditionals

### ISSUE THREAD

**Issue by DrewDennison** [returntocorp/semgrep#374]
@aryx I think we should be able to support this type of dataflow for constants now?

```javascript
const x = "asdf";

if (x === "asdf") {
    console.log("foobar")
}

```

https://sgrep.live/Ken

**Comment by mschwager** [comment]
This works now! https://semgrep.dev/s/weZn/

**Comment by aryx** [comment]
well, what works now? The example of drew ($X === $X) actually does not work, and your example matt does not involve any dataflow. You just look for console.log(...).

**Comment by mschwager** [comment]
Ahh true, I misunderstood the request. Reopening...

**Comment by IagoAbal** [comment]
This one works https://semgrep.dev/s/eLEL, that is using the pattern `"..." === "..."`. This matching does not need any dataflow analysis as far as I can tell, it should have worked already back in April. You can see in the output of `-constant_propagation` that `x`'s value `"asdf"` is known to the matcher. I guess it's something in the matching algorithm, I will take a look.

**Comment by IagoAbal** [comment]
This should be fixable in `Matching_generic.equal_ast_binded_code`, this function fails to see that `x` and `"asdf"` are equal, so the matching fails too.

**Comment by aryx** [comment]
Yep, in theory we should also allow matching metavariables module user-defined equivalences (e.g., 1+2 == 2+1 should be
matched by $X == $X  if we defined the user equivalence $X + $Y <=> $Y + $X (like in Coccinelle).
