### ISSUE TITLE
sgrep-lint API reference

### ISSUE THREAD

**Issue by nbrahms** [returntocorp/semgrep#380]
To make sgrep-lint readily usable by security engineers, the sgrep-lint API should be fully documented.

This should include:

- How to invoke sgrep-lint, as a binary, and as a Docker image
- YAML structure
- Documentation on each key within the YAML schema

**Comment by ulziibay** [comment]
Basically https://github.com/returntocorp/sgrep#quickstart has the docker based workflow documented. https://github.com/returntocorp/sgrep/blob/develop/docs/config.md has the YAML structure documented.

**Comment by mschwager** [comment]
I'm planning on completing this in a few stages:

- [x] Shore up the README - it's important to keep things concise here then point to further documentation when necessary.
- [ ] Unify the [simple](https://github.com/returntocorp/sgrep/blob/develop/docs/config/simple.md) and [advanced](https://github.com/returntocorp/sgrep/blob/develop/docs/config/advanced.md) configuration - IMO the simple info should go in the README, then users who want to learn more can visit the exhaustive advanced info.
- [ ] Minimize information sparse resources. The [integrations](https://github.com/returntocorp/sgrep/blob/develop/docs/integrations.md), [matrix](https://github.com/returntocorp/sgrep/blob/develop/docs/matrix.md), and [contributing](https://github.com/returntocorp/sgrep/blob/develop/CONTRIBUTING.md) docs contain about ~one paragraph each. We should either flesh these out more if they're needed (e.g. can we combine the development and contributing pages?), or move them into the README if they're small pieces of information. Forcing users to jump around for tidbits of information can be a jarring experience.

**Comment by mschwager** [comment]
Woops, this isn't done yet.

**Comment by DrewDennison** [comment]
@mschwager what's your availability for completing this given your other work this week?

**Comment by mschwager** [comment]
I'm going to iterate on the simple docs then I'll call this done :+1:
