### ISSUE TITLE
Implement equivalence classes in sgrep-lint

### ISSUE THREAD

**Issue by nbrahms** [returntocorp/semgrep#385]
Equivalence classes were recently added to sgrep. In order to use these to reduce check-writing cardinality, let's provide a mechanism within sgrep-lint to define these equivalence classes and forward them to sgrep.

**Comment by ulziibay** [comment]
More motivating check examples we can write once we have this feature: https://github.com/securego/gosec/blob/master/rules/sql.go

**Comment by nbrahms** [comment]
Duplicates #363
