### ISSUE TITLE
Registry shows use-frozen-lockfile-pipenv instead of use-frozen-lockfile-pip

### ISSUE THREAD

**Issue by Sjord** [returntocorp/semgrep#5294]
From semgrep results I clicked on the Details link, and that sent me to:

https://semgrep.dev/r?q=generic.ci.security.use-frozen-lockfile.use-frozen-lockfile-pip

When I click the generic.ci.security.use-frozen-lockfile.use-frozen-lockfile-pip row, the inline editor shows use-frozen-lockfile-**pipenv**, where I would expect it to show use-frozen-lockfile-**pip**.

![Screenshot 2022-05-24 at 16 20 40](https://user-images.githubusercontent.com/113030/170058495-e7bf4e8e-461d-4d9e-9dfd-54503a431ed0.png)

**Comment by r2c-demo** [comment]
This issue is synced in Linear at https://linear.app/r2c/issue/PA-1375/registry-shows-use-frozen-lockfile-pipenv-instead-of-use-frozen. _Note_: this link is for r2c use only and is not accessible publicly.

**Comment by Sjord** [comment]
Also, `use-frozen-lockfile-pip` [was renamed recently](https://github.com/returntocorp/semgrep-rules/commit/fd6000169ec1034af400f08872291db87db45522), so I think `use-frozen-lockfile-pip` should be removed from the registry?

**Comment by Sjord** [comment]
@underyx Could you take a look at this?

**Comment by denizdogan** [comment]
Keep this alive

**Comment by Sjord** [comment]
@inkz Could you take a look at this?

**Comment by underyx** [comment]
Sorry I missed the earlier notification, I notified the registry maintainers on our Slack now.

**Comment by denizdogan** [comment]
Not stale

**Comment by LewisArdern** [comment]
Hi Friends!

Sorry this took so long to look at, it must have gotten lost in the weeds, anything to do with registry/rules should realistically head over to https://github.com/returntocorp/semgrep-rules. We will make sure anything is transferred there in the future for cases like this.

We looked at the rule and noticed that it doesn't have a very high fix-rate, so we actually went ahead and deprecated it so this should not longer appear in your scans as a finding. 

If this rule provided you value, and you want a rule like this to exist in the registry, we can introduce a new rule that will be only specific to pipenv, and should be more inline with what it was trying to scan.

Extremely sorry for the tardy response here, and appreciate your persistence in getting it to us to be resolved.

**Comment by Sjord** [comment]
This rule provided me value, and I want a rule like this to exist in the registry.

**Comment by Sjord** [comment]
> When I click the generic.ci.security.use-frozen-lockfile.use-frozen-lockfile-pip row, the inline editor shows use-frozen-lockfile-pipenv, where I would expect it to show use-frozen-lockfile-pip.

 This still happens, so this bug doesn't seem to be solved.
