### ISSUE TITLE
Add "paved road" for pattern unit testing

### ISSUE THREAD

**Issue by dlukeomalley** [returntocorp/semgrep#645]
**Is your feature request related to a problem? Please describe.**
As we (r2c + community) write more patterns, there is a growing desire for a standardized way to write pattern unit tests. There are a few existing efforts:

**semgrep-rules Tests**
r2c has set up infrastructure for doing this in [returntocorp/sgrep-rules](https://github.com/returntocorp/sgrep-rules), which the community can get access to by opening PRs against that repo, but this approach doesn't work for private patterns or patterns tracked in a users own repository (see Zulip's [tools/semgrep.yml](https://github.com/zulip/zulip/blob/1152c372d6ca546026a947632931b3cc8333150f/tools/semgrep.yml))

**semgrep.live True Positive Annotations**
semgrep.live also provides some unit testing capability:

![image](https://user-images.githubusercontent.com/605906/80822207-0b09d780-8b8f-11ea-8281-43696e8ca491.png)

**Zulip good_lines/bad_lines metadata**
See #529

**Describe the solution you'd like**
A native solution that is accessible via the semgrep CLI

**Comment by dlukeomalley** [comment]
#626 may also be related. CC @underyx

**Comment by underyx** [comment]
@dlukeomalley so I just had my first look at `semgrep --test` and it seems like we already have "a native solution that is accessible via the semgrep CLI"? What else are we missing here? Is it only documentation, or do we need any adjustments to the testing feature?

**Comment by underyx** [comment]
@dlukeomalley can we close this out with the following:

- [ ] I act like a customer by re-adding the semgrep rule for semgrep about top-level imports I wrote for #640 
- [ ] I try to include unit tests for the rule with this rule re-adding PR
- [ ] I fix anything that I found annoying as a user in the previous step
- [ ] I document the whole process
