### ISSUE TITLE
As Galinhas do Mod @Roost @Chikens @More Chikens não nascem

### ISSUE THREAD

**Issue by ProzinPlaysYT** [returntocorp/semgrep#8649]
Ultimamente, me deu vontade de baixar uns mods mais uma vez para jogar, e agora, eu fiquei mais de 30 minutos procurando no overworld, e não achei nenhuma galinha.

Eu não tenho os Mods dos Dragões, Zawa, Nem nada ativado, apenas o roost e alguns outros (Nenhum deles fazem aparecer mobs diferentes no mundo)

Gostaria de saber se tem como resolver e se sim, como.

**Comment by ProzinPlaysYT** [comment]
![16940487792232274704624622429739](https://github.com/returntocorp/semgrep/assets/144291747/6ea83b0e-35fa-438d-a591-f007b48cb9ee)

Como retiro esta mensagem em vermelho ?
Me parece ser um erro

**Comment by kopecs** [comment]
Sorry, but I don't think this is the right place for this.
